version: 2.1
# TODO: validate gradle wrapper to guard against malicious jar files
# TODO: investigate into some optimization
executors:
  docker-api29:
    - image: circleci/android:api-29 # no auth needed here, because this is a public image
  working_directory: ~/Readit

jobs:
  static-analysis:
    executor: docker-api29
    steps:
      - checkout
      - run:
          name: Run ktlint check            # first, Run ktlint check
          command: ./gradlew lintKotlin
      - run:
          name: Format files if applicable
          command: ./gradlew ktlintFormat
      - run:
          name: Run androidLint             # second, Run android lint
          command: ./gradlew lintDebug
      - run:
          name: Apply lintFix
          command: ./gradlew lintFix
  build:
    executor: docker-api29
    steps: # there is some investigation to be done here
      - checkout
      - run:
          name: Build the whole project and provide stacktrace
          command: ./gradlew assemble --stacktrace
      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build